**TP1:** Traitement des méthodes de régularisation L2 et ElasticNet

In [1]:
import matplotlib as pt
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("Oumaima Hoummadi - efficacite_energetique_Dataset.csv")

In [3]:
df.head()

Wall_Area   Roof_Area  Window_Area  Overall_Height  Outdoor_Temperature  \
0  388.202617  188.924545    44.013461        3.449571            13.102177   
1  320.007860  192.818625    38.841030        5.417319            14.283884   
2  348.936899  232.989788    57.666632        4.055632             8.869296   
3  412.044660  219.657912    53.562928        5.238103             9.242672   
4  393.377900  219.203946    32.314615        3.594037            13.584071   

    Humidity  Energy_Efficiency_Rating  Noise_Feature_1  Noise_Feature_2  \
0  51.125928                166.376703         0.989088         0.904051   
1  53.690759                148.002019         0.818101         0.035220   
2  48.129687                173.574835         0.340605         0.180661   
3  50.771139                195.742252         0.152047         0.338514   
4  79.116164                168.598360         0.784059         0.577496   

   Noise_Feature_3  ...  Noise_Feature_8  Noise_Feature_9  Noise_Feature_10  \
0         0.791454  ...         0.067229         0.288525          0.518964   
1         0.623867  ...         0.035538         0.571153          0.052572   
2         0.439745  ...         0.420259         0.914694          0.682054   
3         0.010586  ...         0.896694         0.738639          0.268888   
4         0.964928  ...         0.277569         0.856666          0.106768   

   Orientation_East  Orientation_North  Orientation_South  Orientation_West  \
0                 0                  1                  0                 0   
1                 1                  0                  0                 0   
2                 0                  0                  1                 0   
3                 0                  0                  1                 0   
4                 0                  1                  0                 0   

   Glazing_Type_Type_A  Glazing_Type_Type_B  Glazing_Type_Type_C  
0                    0                    1                    0  
1                    0                    0                    1  
2                    0                    0                    1  
3                    0                    1                    0  
4                    0                    1                    0  

[5 rows x 24 columns]

In [4]:
X=df.drop("Energy_Efficiency_Rating",axis=1)
y=df["Energy_Efficiency_Rating"]

In [5]:
X.shape

(200, 23)

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [19]:
y_pred=model.predict(X_train)
y_pred

array([147.50801155, 178.6147079 , 147.25032384, 161.16706181,
       156.28346816, 161.92134993, 121.64395496, 163.38212154,
       132.22012437, 139.74608412, 146.45725199, 199.04256864,
       166.73535369, 119.38703771, 158.06593475, 163.80142758,
       150.71300087, 142.37702624, 166.30429221, 172.03508903,
       173.0834397 , 132.25514659, 137.83207757, 141.128466  ,
       149.77178706, 176.89503453, 175.03370976, 176.85271888,
       132.26475118, 134.32007859, 150.40467451, 149.97887632,
       139.21861116, 120.98356822, 172.33242316, 151.81462346,
       144.69122748, 165.44397775, 136.44603069, 142.83201736,
       171.66927172, 131.40164371, 141.04081983, 159.48499516,
       169.56162297, 181.51192072, 149.90866162, 126.61705005,
       123.36873404, 128.42614252, 131.30003705, 165.09678204,
       187.8431335 , 125.9571116 , 153.09678618, 157.53568427,
       134.47564651, 142.34947119, 148.58875786, 161.16228457,
       122.24989119, 175.89729287, 137.00359261, 141.72

In [20]:
acc_train=r2_score(y_pred,y_train)

In [21]:
y_pred_test=model.predict(X_test)
acc_test=r2_score(y_pred_test,y_test)

In [46]:
(acc_train,acc_test)
# 9%

(0.9451612092275132, 0.8544370240878687)

In [37]:
from sklearn.linear_model import LassoCV
lambda1 = np.linspace(0, 10, 20)  
lassoCV = LassoCV(alphas=lambda1, cv=10, max_iter=1000000)
lassoCV.fit(X_train,y_train)
best_alpha = lassoCV.alpha_
print("best vel alpha ",best_alpha)

c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:681: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1195.9244237206294, tolerance: 4.484421351822108
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:681: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\admin\AppData\

best vel alpha  0.5263157894736842


c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1177.5033654992221, tolerance: 4.639576484312955
  model = cd_fast.enet_coordinate_descent_gram(


In [38]:
coef = pd.DataFrame({
    "feature": X_train.columns,
    "avant L1": model.coef_,
    "après L1": lassoCV.coef_
})

coef

feature  avant L1  après L1
0             Wall_Area  0.302253  0.299125
1             Roof_Area  0.241509  0.245946
2           Window_Area  0.259234  0.261297
3        Overall_Height -0.103891 -0.000000
4   Outdoor_Temperature -0.080775 -0.072988
5              Humidity -0.066741 -0.050996
6       Noise_Feature_1 -1.157413 -0.000000
7       Noise_Feature_2  0.456279  0.000000
8       Noise_Feature_3 -1.231271 -0.000000
9       Noise_Feature_4 -0.009997  0.000000
10      Noise_Feature_5  0.815266  0.000000
11      Noise_Feature_6  1.790095  0.000000
12      Noise_Feature_7 -0.289109 -0.000000
13      Noise_Feature_8  4.026383  0.000000
14      Noise_Feature_9  0.855612  0.000000
15     Noise_Feature_10 -0.977680  0.000000
16     Orientation_East  0.919734  0.000000
17    Orientation_North -0.817762 -0.000000
18    Orientation_South  1.497093  0.000000
19     Orientation_West -1.599065 -0.000000
20  Glazing_Type_Type_A  0.264858  0.000000
21  Glazing_Type_Type_B  0.139014  0.000000
22  Glazing_Type_Type_C -0.403872 -0.000000

In [41]:
from sklearn.linear_model import Lasso
reg_L1 = Lasso(alpha=best_alpha)
reg_L1.fit(X_train, y_train)


Lasso(alpha=np.float64(0.5263157894736842))

In [42]:
y_pred_train_l1=reg_L1.predict(X_train)
y_pred_test_l1=reg_L1.predict(X_test)

In [43]:
acc_train_L1=r2_score(y_pred_train_l1,y_train)
acc_test_L1=r2_score(y_pred_test_l1,y_test)

In [45]:
(acc_train_L1,acc_test_L1)
# 7%

(0.9335338785508511, 0.8621263034822533)

In [45]:
import pandas as pd

import numpy  as np
from sklearn.preprocessing import OneHotEncoder ,  MinMaxScaler
# import seaborn as sns

# encodage_ordinal = {'petite': 1,'moyenne': 2, 'grande': 3}
# decodage_ordianl = {v: k for k, v in encodage_ordinal.items()}
# df  = pd.DataFrame({'taille' : ["petite" , "moyenne" , "grande"]})
# df['taille'] = df['taille'].map(encodage_ordinal)
# df.head()




# Exemple de DataFrame
df2 = pd.DataFrame({'categorie': ['A', 'B', 'C']})

# Initialisation de l'encodeur OneHotEncoder
encoder = OneHotEncoder()
# Encodage des données
encoded = encoder.fit_transform(df2[['categorie']]).toarray()
# Afficher le résultat
print(encoded)

# decoded = encoder.inverse_transform(encoded)

# # Affichage du résultat décodé
# print("\nDecoded data:")
# print(decoded.flatten() , end='\n')

# # Exemple de données
# data = {'col1': [10, 20, 30, 40, 50], 'col2': [200,
# 300, 400, 500, 600]}
# df3 = pd.DataFrame(data)
# print(df3)
# # Normalisation
# scaler = MinMaxScaler()
# df_scaled = scaler.fit_transform(df3)
# # Affichage du résultat
# print(df_scaled)

# n_samples = 10
# np.random.seed(42)
# var1 = np.random.normal(0, 1, n_samples)   # Variable aléatoire (non corrélée)
# var2 = 0.8 * var1 + np.random.normal(0, 0.5, n_samples)  # Corrélée avec var1
# var3 = np.random.normal(10, 5, n_samples)  # Variable aléatoire (non corrélée)
# var4 = 0.1 * var3 + np.random.normal(0, 1, n_samples)  # Faiblement corrélée avec var3
# var5 = np.random.normal(0, 1, n_samples)   # Variable aléatoire (non corrélée)
# df3 = pd.DataFrame({
#     'var1': var1,
#     'var2': var2,  # Fortement corrélée avec var1
#     'var3': var3,
#     'var4': var4,  # Faiblement corrélée avec var3
#     'var5': var5   # Non corrélée
# })

# # Affichage de la matrice de corrélation
# # sns.heatmap(df3.corr(), annot=True)
# print(df3.head(10) , " ok")
# # Matrice de corrélation
# corr_matrix = df3.corr().abs()

# # Créer une liste pour stocker les indices des colonnes à supprimer
# to_drop = []

# # Itérer sur la matrice de corrélation pour trouver les corrélations supérieures à 0.9
# for i in range(len(corr_matrix.columns)):
#     for j in range(i):
#         if corr_matrix.iloc[i, j] > 0.9:  # Si la corrélation est supérieure à 0.9
#             colname = corr_matrix.columns[i]  # Nom de la colonne à supprimer
#             to_drop.append(colname)

# # Supprimer les colonnes identifiées
# df3 = df3.drop(columns=to_drop)
# df3

# import matplotlib.pyplot as plt

# # Visualiser les données dans le nouvel espace réduit
# plt.scatter(df_pca['PC1'], df_pca['PC2'])
# plt.xlabel('PC1')
# plt.ylabel('PC2')
# plt.title('PCA - Projection des données sur les 2 premières composantes principales')
# plt.show()



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

class DataProcessor:
    def __init__(self, file_path):
        self.file_path = file_path
        self.df = None
        self.original_shape = None

    def load_data(self):
        print("Step 1: Loading and examining data...")
        
        # Load the data
        self.df = pd.read_csv(self.file_path)
        self.original_shape = self.df.shape
        
        print("\nDataset Overview:")
        print(f"Shape: {self.df.shape}")
        print("\nColumns:", self.df.columns.tolist())
        print("\nMissing Values:\n", self.df.isnull().sum())
        
        return self

    def check_data_quality(self):
        """
        Step 2: Check data quality
        """
        print("\nStep 2: Checking data quality...")
        
        # Check for duplicates
        duplicates = self.df.duplicated().sum()
        print(f"Number of duplicate rows: {duplicates}")
        
        # Check data types
        print("\nData Types:\n", self.df.dtypes)
        
        # Check basic statistics
        print("\nNumerical Columns Statistics:")
        print(self.df.describe())
        
        return self

    def clean_data(self):
        print("\nStep 3: Cleaning data...")
        
        # Remove duplicates if any
        self.df = self.df.drop_duplicates()
        
        # Handle missing values if any
        if self.df.isnull().sum().any():
            # Fill numerical missing values with median
            numerical_columns = self.df.select_dtypes(include=[np.number]).columns
            self.df[numerical_columns] = self.df[numerical_columns].fillna(self.df[numerical_columns].median())
        
        # Remove outliers using IQR method for numerical columns
        for col in self.df.select_dtypes(include=[np.number]).columns:
            Q1 = self.df[col].quantile(0.25)
            Q3 = self.df[col].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            self.df[col] = np.where(self.df[col] > upper_bound, upper_bound,
                                  np.where(self.df[col] < lower_bound, lower_bound, self.df[col]))
        
        return self

    def generate_report(self):
        print("\nStep 8: Generating final report...")
        
        print("\nFeature Engineering Summary:")
        print(f"Original number of features: {self.original_shape[1]}")
        print(f"Final number of features: {self.df.shape[1]}")
        print(f"\nNew features created:")
        new_features = [col for col in self.df.columns if col not in pd.read_csv(self.file_path).columns]
        for feature in new_features:
            print(f"- {feature}")
        
        return self
    
    def scale_features(self):
        """
        Step 7: Scale features
        """
        print("\nStep 7: Scaling features...")
        
        # Identify numerical columns to scale
        numerical_cols = ['Wall_Area', 'Roof_Area', 'Window_Area', 'Overall_Height',
                         'Outdoor_Temperature', 'Humidity', 'Total_Surface_Area',
                         'Window_to_Wall_Ratio', 'Roof_to_Wall_Ratio', 'Temp_Humidity_Interaction']
        
        # Scale numerical features
        scaler = StandardScaler()
        self.df[numerical_cols] = scaler.fit_transform(self.df[numerical_cols])
        
        return self

    def process_all(self):
        (self.load_data()
         .check_data_quality()
         .clean_data()
         .scale_features()
         .generate_report())
        
        return self.df

# Example usage
if __name__ == "__main__":
    # Replace with your CSV file path
    file_path = "Mohamed Belannab - efficacite_energetique_Dataset.csv"
    
    try:
        # Create processor and run all steps
        processor = DataProcessor(file_path)
        processed_df = processor.process_all()
        
        print("\nProcessing completed successfully!")
        
    except Exception as e:
        print(f"Error during processing: {str(e)}")

Step 1: Loading and examining data...

Step 2: Checking data quality...
Number of duplicate rows: 0

Data Types:
 Wall_Area                   float64
Roof_Area                   float64
Window_Area                 float64
Overall_Height              float64
Outdoor_Temperature         float64
Humidity                    float64
Energy_Efficiency_Rating    float64
Noise_Feature_1             float64
Noise_Feature_2             float64
Noise_Feature_3             float64
Noise_Feature_4             float64
Noise_Feature_5             float64
Noise_Feature_6             float64
Noise_Feature_7             float64
Noise_Feature_8             float64
Noise_Feature_9             float64
Noise_Feature_10            float64
Orientation_East              int64
Orientation_North             int64
Orientation_South             int64
Orientation_West              int64
Glazing_Type_Type_A           int64
Glazing_Type_Type_B           int64
Glazing_Type_Type_C           int64
dtype: object

Numeric